### ISSUE TITLE
Modify the distance of detection

### ISSUE THREAD

**Issue by FrankGaul** [Seeed-Studio/PIR_Motion_Sensor#5]
I wish to adjust the distance of detection of the Grove PIR Motion Sensor. I have to add a potentiometer
but what value? Thank you very much

**Comment by lanselambor** [comment]
![pir_motion](https://user-images.githubusercontent.com/9337688/39222302-9441412a-486e-11e8-8c0b-3fd7e56cde89.png)

According to the descripption inside [schematic file](https://github.com/SeeedDocument/Grove_PIR_Motion_Sensor/raw/master/resources/Grove_PIR_Sensor_v1.2.pdf), to solder potentiometers of R2(2M), R6(10K), you should remove R13 and R14.
